-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 17:47:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(30) NOT NULL,
  `description` VARCHAR(50) NULL,
  `email` VARCHAR(50) NOT NULL,
  `profile_image` VARCHAR(255) NOT NULL,
  `role` VARCHAR(5) NOT NULL,
  `skill` VARCHAR(30) NULL,
  `position` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickName_UNIQUE` (`nickName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`follow` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `follower_id` BIGINT NOT NULL,
  `following_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `follower_id_idx` (`follower_id` ASC) VISIBLE,
  INDEX `following_id_idx` (`following_id` ASC) VISIBLE,
  CONSTRAINT `follower_id`
    FOREIGN KEY (`follower_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `following_id`
    FOREIGN KEY (`following_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`court`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`court` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `basket_count` INT(10) NULL,
  `texture` VARCHAR(30) NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`new_court`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`new_court` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `image` VARCHAR(255) NULL,
  `basket_count` INT(10) NOT NULL,
  `texture` VARCHAR(30) NULL,
  `address` VARCHAR(255) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `court_id` BIGINT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `has_ball` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `court_id_idx` (`court_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `court_id`
    FOREIGN KEY (`court_id`)
    REFERENCES `mydb`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorite` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `court_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `court_id_idx` (`court_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `court_id`
    FOREIGN KEY (`court_id`)
    REFERENCES `mydb`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alarmSpeaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alarmSpeaker` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `court_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `reservation_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `court_id_idx` (`court_id` ASC) VISIBLE,
  INDEX `reveration_id_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `court_id`
    FOREIGN KEY (`court_id`)
    REFERENCES `mydb`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reveration_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `mydb`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chatTitle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chatTitle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `court_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `court_id_idx` (`court_id` ASC) VISIBLE,
  CONSTRAINT `court_id`
    FOREIGN KEY (`court_id`)
    REFERENCES `mydb`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chatDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chatDetails` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `chat_title_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chat_title_id_idx` (`chat_title_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `chat_title_id`
    FOREIGN KEY (`chat_title_id`)
    REFERENCES `mydb`.`chatTitle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userCourtMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userCourtMapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `court_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `court_id_idx` (`court_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `court_id`
    FOREIGN KEY (`court_id`)
    REFERENCES `mydb`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alarmMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alarmMessage` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
