version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/arm64
    container_name: dev-slam
    hostname: root
    restart: always
    ports:
      - "11112:3306"
    networks:
      - dev-slam
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slam
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - dev-slam:/var/lib/mysql

volumes:
  dev-slam:

networks:
  dev-slam:
    driver: bridge